version: "3.8"

services:
  backend:

  frontend:
    image: "nginx:stable-bookworm-perl"
    container_name: nginx-web
    ports:
      - "90:80"
    volumes:
      - "./frontend/dist:/usr/share/nginx/html"
      - "./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - web-ai-net
networks:
  web-ai-net:
    name: web-ai-net
