spring:
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://mysql:3306/tlias
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  #上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # console output color
  output:
    ansi:
      enabled=ALWAYS

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG

# Mybatis相关配置
mybatis:
  # mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.franklin.web-ai.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云
aliyun:
  oss:
    endpoint: "https://oss-cn-beijing.aliyuncs.com"
    region: "cn-beijing"
    bucketName: "java-web-ai-frank"

