spring:
  # 数据库连接信息
  datasource:
#    url: jdbc:mysql://localhost:3306/tlias?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://34.80.101.122:3306/web_app1?useSSL=false&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql:///web_app1?cloudSqlInstance=franklin-product-web-app-1:asia-east1:mysql8-web-database&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://google/web_app1?cloudSqlInstance=franklin-product-web-app-1:asia-east1:mysql8-web-database&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
#    url: jdbc:mysql://127.0.0.1:3307/web_app1?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
#    password: password
    password: franklinproduct1DB!
    driver-class-name: com.mysql.cj.jdbc.Driver

  #上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # console output color
  output:
    ansi:
      enabled=ALWAYS

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG

# Mybatis相关配置
mybatis:
  # mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.franklin.web-ai.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云
aliyun:
  oss:
    endpoint: "https://oss-cn-beijing.aliyuncs.com"
    region: "cn-beijing"
    bucketName: "java-web-ai-frank"

